
Hero.destroy_all
Team.destroy_all

radiant = Team.create(name: 'Radiant', is_radiant: true)
dire = Team.create(name: 'Dire', is_radiant: false)
unpicked = Team.create(name: 'unpicked', is_radiant: false)

rubick = radiant.heros.create(name: 'Rubick', primary: 'int', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/rubick_full.png?v=4085826?v=4085826', description: 'Strong support, prioritize blink dagger for positioning and spell steal, farm permitting.', playing: 'be aware of type of dmg enemy team has (magic = higher level of passive) and ideal spells to steal (not always ultimates).', with: 'be ready for telekenesis to pull enemy out of position.', against: 'Use a less desirable spell IMMEDIATELY after using a strong spell to keep from Rubick steal.', complexity: 3)
puck = radiant.heros.create(name: 'Puck', primary: 'int', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/puck_full.png?v=4085826?v=4085826', description: 'Strong mid or offlane hero. Very fragile yet extremely illusive. ', playing: 'Win your mid-lane matchup with strong base dmg, start rotating at level 6 (sometimes earlier with HASTE or DOUBLE DMG rune) -- NOTE: You can still fight with 100hp if you manage your skill/items properly.', with: 'If being pressured by enemy supports mid, help out then allow to create opportunities.', against: 'Call out missing from lane and do not chase, way too elusive.', complexity: 3)
shaker = radiant.heros.create(name: 'Shaker', primary: 'str', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_full.png?v=4085826?v=4085826', description: 'All around hero that can be played in any role (carry, support, mid, offlane).', playing: 'In most cases, prioritize blink dagger as he relies heavily on positioning. ', with: 'Entice enemy team to group up for an ES Echoslam counter-initiation.', against: 'Do not group up and look to punish pre blink dagger.', complexity: 2)
sniper = dire.heros.create(name: 'Sniper', primary: 'agi', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/sniper_full.png?v=4085826?v=4085826', description: 'Mid hero that needs time to farm. Positioning is everything, easy learning curve, hard to be effective.', playing: 'Use shrapnel to keep lane controlled and utilize range to harass safely.', with: 'Create buffer of heroes in front of sniper to protect him.', against: 'If do not have a gap closing hero, be aware of sniper positioning and try take him out soon as his dmg quickly racks up and projectiles are hard to see.', complexity: 1)
doom = unpicked.heros.create(name: 'Doombringer', primary: 'str', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_full.png?v=4085826?v=4085826', description: 'The ultimate disabler, removes ability to use any skills and items.', playing: 'Be aware of what enemy hero needs to be doomed (most of the time its a support in the backlines).', with: 'Call out useful creeps for him to devour (most of the time its a passive).', against: 'Beware of DOOM, call out who is most likely the best target and ensure strong positioning.', complexity: 2)
cm = radiant.heros.create(name: 'Crystal Maiden', primary: 'int', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_full.png?v=4085826?v=4085826', description: 'Easy hero to learn and be effective on.  Very squishy, relies on positioning.', playing: 'You are very strong early, utilize frostbite for easy kills with higher dmg teammates, gank early and often with occasional jungle creep kill in transition.', with: 'Call for CM ganks with smoke.', against: 'Beware of movements, very slow base movement speed, early boots or windlace should be enough to keep at bay.', complexity: 1)
lina = dire.heros.create(name: 'Lina', primary: 'int', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/lina_full.png?v=4085826?v=4085826', description: 'All around hero, with massive amounts of magical nuke and can turn into right clicker with stacks of fiery soul in mid-late game. ', playing: 'As core, do not be afraid to use Dragon Slave to farm full creep waves and harass.', with: 'Try to setup enemy for an easy Light Strike Array.', against: 'Force Lina to panic, do not let her get many spells off -- she struggles against mobile heroes', complexity: 2)
windranger = dire.heros.create(name: 'WindRanger', primary: 'int', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_full.png?v=4085826?v=4085826', description: 'Int-based right clicker who is elusive and requires enemy to get truestrike items. Heavily Skill Shot Focused.', playing: 'use focus fire to chip through heroes or objectives. Blink dagger is useful for positioning for a 2 hero shackle shot or tree latch.', with: 'Level dependent. Help her get levels for effectiveness.', against: 'do not line up for easy 2 hero shackles and use magical nukes to kill or get truestrike items.', complexity: 2)
enigma = dire.heros.create(name: 'Enigma', primary: 'int', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/enigma_full.png?v=4085826?v=4085826', description: 'Most often jungled but very effective as an offlane hero. Most known for BLACKHOLE.', playing: 'Mek is most often the best first item to build althought most build blink first. Pressure towers with eidolons and mek for gold infusion.', with: 'When mek is up, help pressure towers to create space for friendly Carry.', against: 'DO NOT GROUP UP IN FIGHTS! EVER! and shut down early, if in jungle, block camps if in line pressure early as he is slow and weak.', complexity: 2)
am = radiant.heros.create(name: 'Anti-Mage', primary: 'agi', image: 'http://cdn.dota2.com/apps/dota2/images/heroes/antimage_full.png?v=4085826?v=4085826', description: 'Can solo carry a game if fully farmed, extremely elusive and heavily farm dependent.', playing: 'Do not aim for the 9minute battlefury, the best way is to buy a few cost effective items to protect from early ganks. Know when to split push, always apply pressure.', with: 'Draw attention away from AM while he freefarms his items, do not get upset if he does not join early fights.', against: 'Pressure him constantly ensure that you have crowd-control to keep him from blinking away. Prioritize strong right click and low mana pool.', complexity: 1)
